apiVersion: 1
datasources:
  - name: ClickHouse Traces
    uid: clickhouse-traces
    type: grafana-clickhouse-datasource
    access: proxy
    isDefault: true
    editable: false
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      secure: false
      username: grafana
      defaultDatabase: otel
      dialTimeout: "10"
      queryTimeout: "10"
      validateSql: true
      traces:
        defaultDatabase: otel
        defaultTable: otel_traces
        otelEnabled: true
        traceIdColumn: TraceId
        spanIdColumn: SpanId
        operationNameColumn: SpanName
        parentSpanIdColumn: ParentSpanId
        serviceNameColumn: ServiceName
        durationColumn: Duration
        startTimeColumn: Timestamp
    secureJsonData:
      password: workshop
